/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/setuptools/_distutils/version.py
[09/17 00:46:42 detectron2]: Rank of current process: 0. World size: 4
[09/17 00:46:42 detectron2]: Full config saved to checkpoints/voc/1726530394/fsod1/1shot/seed1/config.yaml
[09/17 00:46:43 fvcore.common.checkpoint]: [Checkpointer] Loading from ./pretrain/R-101.pkl ...
[09/17 00:46:43 fvcore.common.checkpoint]: Reading a file from 'torchvision'
[09/17 00:46:49 detectron2]: Loss: 0.0000
[09/17 00:46:49 detectron2]: [CLS] Use dropout: p = 0.8
[09/17 00:46:49 detectron2]: [Refine] n = 24, α = 0.1
[09/17 00:46:49 d2.data.build]: Removed 0 images with no usable annotations. 20 images left.
[09/17 00:46:49 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=..., max_size=1333, sample_style='choice'), RandomFlip()]
[09/17 00:46:49 d2.data.build]: Using training sampler TrainingSampler
[09/17 00:46:50 d2.data.common]: Serializing 20 elements to byte tensors and concatenating them all ...
[09/17 00:46:50 d2.data.common]: Serialized dataset takes 0.01 MiB
[09/17 00:46:50 fvcore.common.checkpoint]: [Checkpointer] Loading from checkpoints/voc/1726530394/base1/model_final-fsod.pth ...
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    launch(
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/users/acr23hk/paper/fsod-dc/main.py", line 29, in main
    trainer.resume_or_load(resume=args.resume)
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 412, in resume_or_load
    self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume)
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 227, in resume_or_load
    return self.load(path, checkpointables=[])
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 52, in load
    ret = super().load(path, *args, **kwargs)
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 153, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint checkpoints/voc/1726530394/base1/model_final-fsod.pth not found!

/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/setuptools/_distutils/version.py
[09/17 00:46:59 detectron2]: Rank of current process: 0. World size: 4
[09/17 00:46:59 detectron2]: Full config saved to checkpoints/voc/1726530394/fsod1/2shot/seed1/config.yaml
[09/17 00:47:00 fvcore.common.checkpoint]: [Checkpointer] Loading from ./pretrain/R-101.pkl ...
[09/17 00:47:00 fvcore.common.checkpoint]: Reading a file from 'torchvision'
[09/17 00:47:07 detectron2]: Loss: 0.0002
[09/17 00:47:07 detectron2]: [CLS] Use dropout: p = 0.8
[09/17 00:47:07 detectron2]: [Refine] n = 24, α = 0.1
[09/17 00:47:07 d2.data.build]: Removed 0 images with no usable annotations. 40 images left.
[09/17 00:47:07 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=..., max_size=1333, sample_style='choice'), RandomFlip()]
[09/17 00:47:07 d2.data.build]: Using training sampler TrainingSampler
[09/17 00:47:07 d2.data.common]: Serializing 40 elements to byte tensors and concatenating them all ...
[09/17 00:47:07 d2.data.common]: Serialized dataset takes 0.01 MiB
[09/17 00:47:08 fvcore.common.checkpoint]: [Checkpointer] Loading from checkpoints/voc/1726530394/base1/model_final-fsod.pth ...
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    launch(
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/users/acr23hk/paper/fsod-dc/main.py", line 29, in main
    trainer.resume_or_load(resume=args.resume)
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 412, in resume_or_load
    self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume)
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 227, in resume_or_load
    return self.load(path, checkpointables=[])
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 52, in load
    ret = super().load(path, *args, **kwargs)
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 153, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint checkpoints/voc/1726530394/base1/model_final-fsod.pth not found!

/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/setuptools/_distutils/version.py
[09/17 00:47:18 detectron2]: Rank of current process: 0. World size: 4
[09/17 00:47:18 detectron2]: Full config saved to checkpoints/voc/1726530394/fsod1/3shot/seed1/config.yaml
[09/17 00:47:19 fvcore.common.checkpoint]: [Checkpointer] Loading from ./pretrain/R-101.pkl ...
[09/17 00:47:19 fvcore.common.checkpoint]: Reading a file from 'torchvision'
[09/17 00:47:27 detectron2]: Loss: 0.0003
[09/17 00:47:27 detectron2]: [CLS] Use dropout: p = 0.8
[09/17 00:47:27 detectron2]: [Refine] n = 24, α = 0.1
[09/17 00:47:28 d2.data.build]: Removed 0 images with no usable annotations. 60 images left.
[09/17 00:47:28 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=..., max_size=1333, sample_style='choice'), RandomFlip()]
[09/17 00:47:28 d2.data.build]: Using training sampler TrainingSampler
[09/17 00:47:28 d2.data.common]: Serializing 60 elements to byte tensors and concatenating them all ...
[09/17 00:47:28 d2.data.common]: Serialized dataset takes 0.02 MiB
[09/17 00:47:29 fvcore.common.checkpoint]: [Checkpointer] Loading from checkpoints/voc/1726530394/base1/model_final-fsod.pth ...
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    launch(
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/users/acr23hk/paper/fsod-dc/main.py", line 29, in main
    trainer.resume_or_load(resume=args.resume)
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 412, in resume_or_load
    self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume)
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 227, in resume_or_load
    return self.load(path, checkpointables=[])
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 52, in load
    ret = super().load(path, *args, **kwargs)
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 153, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint checkpoints/voc/1726530394/base1/model_final-fsod.pth not found!

/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/setuptools/_distutils/version.py
[09/17 00:47:39 detectron2]: Rank of current process: 0. World size: 4
[09/17 00:47:39 detectron2]: Full config saved to checkpoints/voc/1726530394/fsod1/5shot/seed1/config.yaml
[09/17 00:47:40 fvcore.common.checkpoint]: [Checkpointer] Loading from ./pretrain/R-101.pkl ...
[09/17 00:47:40 fvcore.common.checkpoint]: Reading a file from 'torchvision'
[09/17 00:47:50 detectron2]: Loss: 0.0005
[09/17 00:47:50 detectron2]: [CLS] Use dropout: p = 0.8
[09/17 00:47:50 detectron2]: [Refine] n = 24, α = 0.1
[09/17 00:47:50 d2.data.build]: Removed 0 images with no usable annotations. 100 images left.
[09/17 00:47:50 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=..., max_size=1333, sample_style='choice'), RandomFlip()]
[09/17 00:47:50 d2.data.build]: Using training sampler TrainingSampler
[09/17 00:47:50 d2.data.common]: Serializing 100 elements to byte tensors and concatenating them all ...
[09/17 00:47:50 d2.data.common]: Serialized dataset takes 0.03 MiB
[09/17 00:47:50 fvcore.common.checkpoint]: [Checkpointer] Loading from checkpoints/voc/1726530394/base1/model_final-fsod.pth ...
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    launch(
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/users/acr23hk/paper/fsod-dc/main.py", line 29, in main
    trainer.resume_or_load(resume=args.resume)
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 412, in resume_or_load
    self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume)
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 227, in resume_or_load
    return self.load(path, checkpointables=[])
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 52, in load
    ret = super().load(path, *args, **kwargs)
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 153, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint checkpoints/voc/1726530394/base1/model_final-fsod.pth not found!

/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/setuptools/_distutils/version.py
[09/17 00:48:00 detectron2]: Rank of current process: 0. World size: 4
[09/17 00:48:00 detectron2]: Full config saved to checkpoints/voc/1726530394/fsod1/10shot/seed1/config.yaml
[09/17 00:48:01 fvcore.common.checkpoint]: [Checkpointer] Loading from ./pretrain/R-101.pkl ...
[09/17 00:48:01 fvcore.common.checkpoint]: Reading a file from 'torchvision'
[09/17 00:48:18 detectron2]: Loss: 0.0010
[09/17 00:48:18 detectron2]: [CLS] Use dropout: p = 0.8
[09/17 00:48:18 detectron2]: [Refine] n = 24, α = 0.1
[09/17 00:48:18 d2.data.build]: Removed 0 images with no usable annotations. 200 images left.
[09/17 00:48:18 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=..., max_size=1333, sample_style='choice'), RandomFlip()]
[09/17 00:48:18 d2.data.build]: Using training sampler TrainingSampler
[09/17 00:48:18 d2.data.common]: Serializing 200 elements to byte tensors and concatenating them all ...
[09/17 00:48:18 d2.data.common]: Serialized dataset takes 0.05 MiB
[09/17 00:48:18 fvcore.common.checkpoint]: [Checkpointer] Loading from checkpoints/voc/1726530394/base1/model_final-fsod.pth ...
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    launch(
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/users/acr23hk/paper/fsod-dc/main.py", line 29, in main
    trainer.resume_or_load(resume=args.resume)
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 412, in resume_or_load
    self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume)
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 227, in resume_or_load
    return self.load(path, checkpointables=[])
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 52, in load
    ret = super().load(path, *args, **kwargs)
  File "/users/acr23hk/.conda/envs/paper1/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 153, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint checkpoints/voc/1726530394/base1/model_final-fsod.pth not found!

